# This is a basic workflow to help you get started with Actions
name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Hello World 1
        
      # name: Simulate an error
      # run: echo "About to fail" ; exit 1

      - name: Another greeting
        run: echo "Hello, World 2"
        
      - name: Install
        run: npm install
        
        
      - name: Build
        run: npm run build
